image: node:14.16.0-alpine3.10

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - install
  - build
  - test
  - lint

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - "sellpoint_frontend/.yarn"
    - "sellpoint_frontend/node_modules"
    - "sellpoint_frontend/packages/*/node_modules"
    - ".cache/pip"
    - "sellpoint_backend/venv/"

frontend-install:
  stage: install
  before_script:
    - cd sellpoint_frontend
  script:
    - echo 'Installing dependencies...'
    - yarn install --cache-folder .yarn

frontend-build:
  stage: build
  before_script:
    - cd sellpoint_frontend
  script: yarn build

frontend-test:
  stage: test
  before_script:
    - cd sellpoint_frontend
  script: yarn test

backend-test:
  stage: test
  image: python:latest
  before_script:
    - cd sellpoint_backend
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - python manage.py test

frontend-lint:
  stage: lint
  before_script:
    - cd sellpoint_frontend
  script: yarn lint:ci

backend-lint:
  stage: lint
  image: python:latest
  before_script:
    - cd sellpoint_backend
    - source venv/bin/activate
  script:
    - python -m black ./ --check