image: node:14.16.0-alpine3.10

variables:
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/.cache/yarn"

stages:
  - build
  - test
  - lint

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ".cache/*"
    - "sellpoint_frontend/node_modules/*"

frontend-build:
  stage: build
  before_script:
    - cd sellpoint_frontend
    - yarn install --non-interactive --production=false
  script: yarn build

frontend-test:
  stage: test
  needs: ["frontend-build"]
  before_script:
    - cd sellpoint_frontend
    - yarn install --non-interactive --production=false
  cache:
    policy: pull
  script: yarn test

backend-test:
  stage: test
  image: python:3.9.2
  before_script:
    - cd sellpoint_backend
    - pip install -r requirements.txt
  script:
    - python manage.py test

frontend-lint:
  stage: lint
  needs: ["frontend-test"]
  before_script:
    - cd sellpoint_frontend
    - yarn install --non-interactive --production=false
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
  script: yarn lint:ci

backend-lint:
  stage: lint
  needs: ["backend-test"]
  image: python:3.9.2
  before_script:
    - cd sellpoint_backend
    - pip install -r requirements.txt
  script:
    - python -m black ./ --check