# Generated by Django 3.1.6 on 2021-02-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellpoint_ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Is sold'),
        ),
    ]
