# Generated by Django 3.1.6 on 2021-03-24 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sellpoint_ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteAd",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favorite_ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sellpoint_ads.ad",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "favorite_ad")},
            },
        ),
    ]
