# Generated by Django 3.1.6 on 2021-03-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellpoint_ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
